services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: svp
      POSTGRES_PASSWORD: svp
      POSTGRES_DB: svpdb
    ports:
      - "5432:5432"
    volumes:
      - svp_pgdata:/var/lib/postgresql/data
volumes:
  svp_pgdata:
